# This is a basic workflow to help you get started with Actions

name: build

# Controls when the workflow will run
on: 
  push:
    branches: 
      - '**'
      - '!experimental'
  
  pull_request:
    branches:
      - '!experimental'
      - '**'

  # Allows you to run this workflow manually from the Actions tab    
  workflow_dispatch:
    inputs:
      enable-debug-logs:
        description: 'enable additional debug output during workflow execution'
        default: false
        required: false
        type: boolean

defaults:
  run:
    shell: pwsh
    
env:
  debug-enabled: ${{ github.event.inputs.enable-debug-logs }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Environment Variables
        if: ${{ env.debug-enabled == true }}
        run: |
          Get-ChildItem env:
        shell: pwsh

      - name: get Directory info
        run: pwd

      - name: additional debug
        run: |
          get-childitem env:

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

